name: Release

on:
  - workflow_dispatch

jobs:
  release:
    runs-on: ubuntu-22.04
    steps:
      - name: Create Draft Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: draft
          release_name: Release Draft
          draft: true
          prerelease: true
    outputs:
      upload_url: ${{ steps.create_release.outputs.upload_url }}

  build:
    runs-on: ubuntu-22.04
    needs: release

    env:
      CC: clang
      CXX: clang++
      NDK_VERSION: 25.1.8937393
    
    strategy:
      matrix:
        build_type: [Debug, RelWithDebInfo]
        target: [native, android]

    steps:
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install meson

      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Build Natively
        if: matrix.target == 'native'
        env:
          BUILD_TYPE: ${{ matrix.build_type }}
        run: |
          touch local.mk
          make native

      - name: Build for Android
        if: matrix.target == 'android'
        env:
          BUILD_TYPE: ${{ matrix.build_type }}
        run: |
          echo "ndk_version := $NDK_VERSION" > local.mk
          echo "ndk_dir     := /usr/local/lib/android/sdk/ndk/$NDK_VERSION" >> local.mk
          make android
      
      - name: Archive
        run: |
          export ZIP_FILE=${{ matrix.target }}-${{ matrix.build_type }}.zip
          zip -r $ZIP_FILE ./${{ matrix.target }}/${{ matrix.build_type }}/

      - name: Upload Release Asset
        id: upload-release-asset 
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ needs.release.outputs.upload_url }}
          asset_path: ${{ matrix.target }}-${{ matrix.build_type }}.zip
          asset_name: ${{ matrix.target }}-${{ matrix.build_type }}.zip
          asset_content_type: application/zip
